#!/bin/sh
#Compilation script for configuring libxml2-2.7.2 on GCC
#############################################################################################
./configure --build=i686-pc-linux \
            --with-endianness=little \
            --enable-shared=no \
            --prefix=`pwd`/../../libs/bin/libxml2-2.7.2/generic/i686-linux \
            CC=gcc \
            AR=ar \
            --without-zlib \
            --without-python

. ./configscript_libxml2_build            
########################################################################################
